# main.py -- put your code here!
# CTRL-D to reboot

import watch
import pyb
import machine
import ssd1306
from pyb import ADC

i2c = machine.SoftI2C(scl=machine.Pin('B8'), sda=machine.Pin('B9'))
oled = ssd1306.SSD1306_I2C(128, 64, i2c)

def LEDsOn():
    pyb.LED(1).on()
    pyb.LED(2).on()
    pyb.LED(3).on()

def LEDsOff():
    pyb.LED(1).off()
    pyb.LED(2).off()
    pyb.LED(3).off()

def LCD(text):
    oled.fill(0)
    oled.text(text, 0, 0)
    oled.show()

def ClearLCD():
    oled.fill(0)

def LCDamogus():
    oled.fill(0)

    offset_x = 50
    offset_y = 10

    oled.pixel(25 + offset_x,15 + offset_y,1)
    oled.pixel(25 + offset_x,14 + offset_y,1)
    oled.pixel(24 + offset_x,13 + offset_y,1)
    oled.pixel(24 + offset_x,12 + offset_y,1)
    oled.pixel(23 + offset_x,11 + offset_y,1)
    oled.pixel(22 + offset_x,10 + offset_y,1)
    oled.pixel(21 + offset_x,9 + offset_y,1)
    oled.pixel(20 + offset_x,9 + offset_y,1)
    oled.pixel(19 + offset_x,8 + offset_y,1)
    oled.pixel(18 + offset_x,8 + offset_y,1)
    oled.pixel(17 + offset_x,8 + offset_y,1)
    oled.pixel(16 + offset_x,8 + offset_y,1)
    oled.pixel(15 + offset_x,8 + offset_y,1)
    oled.pixel(14 + offset_x,8 + offset_y,1)
    oled.pixel(13 + offset_x,8 + offset_y,1)
    oled.pixel(12 + offset_x,8 + offset_y,1)
    oled.pixel(11 + offset_x,9 + offset_y,1)
    oled.pixel(10 + offset_x,10 + offset_y,1)
    oled.pixel(10 + offset_x,11 + offset_y,1)
    oled.pixel(10 + offset_x,12 + offset_y,1)
    oled.pixel(10 + offset_x,13 + offset_y,1)
    oled.pixel(9 + offset_x,14 + offset_y,1)
    oled.pixel(9 + offset_x,15 + offset_y,1)
    oled.pixel(9 + offset_x,16 + offset_y,1)
    oled.pixel(9 + offset_x,17 + offset_y,1)
    oled.pixel(8 + offset_x,18 + offset_y,1)
    oled.pixel(8 + offset_x,19 + offset_y,1)
    oled.pixel(8 + offset_x,20 + offset_y,1)
    oled.pixel(8 + offset_x,21 + offset_y,1)
    oled.pixel(8 + offset_x,22 + offset_y,1)
    oled.pixel(8 + offset_x,23 + offset_y,1)
    oled.pixel(8 + offset_x,24 + offset_y,1)
    oled.pixel(7 + offset_x,25 + offset_y,1)
    oled.pixel(7 + offset_x,26 + offset_y,1)
    oled.pixel(7 + offset_x,27 + offset_y,1)
    oled.pixel(7 + offset_x,28 + offset_y,1)
    oled.pixel(7 + offset_x,29 + offset_y,1)
    oled.pixel(7 + offset_x,30 + offset_y,1)
    oled.pixel(7 + offset_x,31 + offset_y,1)
    oled.pixel(7 + offset_x,32 + offset_y,1)
    oled.pixel(6 + offset_x,32 + offset_y,1)
    oled.pixel(5 + offset_x,31 + offset_y,1)
    oled.pixel(4 + offset_x,31 + offset_y,1)
    oled.pixel(3 + offset_x,32 + offset_y,1)
    oled.pixel(2 + offset_x,32 + offset_y,1)
    oled.pixel(2 + offset_x,33 + offset_y,1)
    oled.pixel(2 + offset_x,34 + offset_y,1)
    oled.pixel(2 + offset_x,35 + offset_y,1)
    oled.pixel(3 + offset_x,36 + offset_y,1)
    oled.pixel(4 + offset_x,36 + offset_y,1)
    oled.pixel(5 + offset_x,37 + offset_y,1)
    oled.pixel(6 + offset_x,37 + offset_y,1)
    oled.pixel(7 + offset_x,37 + offset_y,1)
    oled.pixel(8 + offset_x,37 + offset_y,1)
    oled.pixel(9 + offset_x,36 + offset_y,1)
    oled.pixel(10 + offset_x,36 + offset_y,1)
    oled.pixel(11 + offset_x,36 + offset_y,1)
    oled.pixel(12 + offset_x,35 + offset_y,1)
    oled.pixel(13 + offset_x,34 + offset_y,1)
    oled.pixel(13 + offset_x,33 + offset_y,1)
    oled.pixel(13 + offset_x,32 + offset_y,1)
    oled.pixel(12 + offset_x,31 + offset_y,1)
    oled.pixel(12 + offset_x,30 + offset_y,1)
    oled.pixel(12 + offset_x,29 + offset_y,1)
    oled.pixel(13 + offset_x,28 + offset_y,1)
    oled.pixel(14 + offset_x,28 + offset_y,1)
    oled.pixel(15 + offset_x,28 + offset_y,1)
    oled.pixel(16 + offset_x,28 + offset_y,1)
    oled.pixel(17 + offset_x,28 + offset_y,1)
    oled.pixel(18 + offset_x,28 + offset_y,1)
    oled.pixel(19 + offset_x,28 + offset_y,1)
    oled.pixel(19 + offset_x,29 + offset_y,1)
    oled.pixel(19 + offset_x,30 + offset_y,1)
    oled.pixel(19 + offset_x,31 + offset_y,1)
    oled.pixel(19 + offset_x,32 + offset_y,1)
    oled.pixel(19 + offset_x,33 + offset_y,1)
    oled.pixel(19 + offset_x,34 + offset_y,1)
    oled.pixel(18 + offset_x,34 + offset_y,1)
    oled.pixel(17 + offset_x,34 + offset_y,1)
    oled.pixel(15 + offset_x,35 + offset_y,1)
    oled.pixel(15 + offset_x,36 + offset_y,1)
    oled.pixel(15 + offset_x,37 + offset_y,1)
    oled.pixel(16 + offset_x,38 + offset_y,1)
    oled.pixel(17 + offset_x,38 + offset_y,1)
    oled.pixel(18 + offset_x,38 + offset_y,1)
    oled.pixel(19 + offset_x,38 + offset_y,1)
    oled.pixel(20 + offset_x,38 + offset_y,1)
    oled.pixel(21 + offset_x,38 + offset_y,1)
    oled.pixel(22 + offset_x,38 + offset_y,1)
    oled.pixel(23 + offset_x,38 + offset_y,1)
    oled.pixel(24 + offset_x,37 + offset_y,1)
    oled.pixel(25 + offset_x,37 + offset_y,1)
    oled.pixel(26 + offset_x,36 + offset_y,1)
    oled.pixel(27 + offset_x,35 + offset_y,1)
    oled.pixel(27 + offset_x,34 + offset_y,1)
    oled.pixel(27 + offset_x,33 + offset_y,1)
    oled.pixel(27 + offset_x,32 + offset_y,1)
    oled.pixel(27 + offset_x,31 + offset_y,1)
    oled.pixel(27 + offset_x,30 + offset_y,1)
    oled.pixel(27 + offset_x,29 + offset_y,1)
    oled.pixel(26 + offset_x,28 + offset_y,1)
    oled.pixel(26 + offset_x,27 + offset_y,1)
    oled.pixel(26 + offset_x,26 + offset_y,1)
    oled.pixel(26 + offset_x,25 + offset_y,1)
    oled.pixel(26 + offset_x,24 + offset_y,1)
    oled.pixel(26 + offset_x,23 + offset_y,1)
    oled.pixel(26 + offset_x,22 + offset_y,1)
    oled.pixel(26 + offset_x,21 + offset_y,1)
    oled.pixel(25 + offset_x,20 + offset_y,1)
    oled.pixel(25 + offset_x,19 + offset_y,1)
    oled.pixel(25 + offset_x,18 + offset_y,1)
    oled.pixel(25 + offset_x,17 + offset_y,1)
    oled.pixel(25 + offset_x,16 + offset_y,1)

    oled.pixel(13 + offset_x,13 + offset_y,1)
    oled.pixel(14 + offset_x,13 + offset_y,1)
    oled.pixel(15 + offset_x,13 + offset_y,1)
    oled.pixel(16 + offset_x,13 + offset_y,1)
    oled.pixel(17 + offset_x,13 + offset_y,1)
    oled.pixel(18 + offset_x,13 + offset_y,1)
    oled.pixel(19 + offset_x,13 + offset_y,1)
    oled.pixel(20 + offset_x,13 + offset_y,1)
    oled.pixel(13 + offset_x,14 + offset_y,1)
    oled.pixel(13 + offset_x,15 + offset_y,1)
    oled.pixel(13 + offset_x,16 + offset_y,1)
    oled.pixel(14 + offset_x,16 + offset_y,1)
    oled.pixel(15 + offset_x,16 + offset_y,1)
    oled.pixel(16 + offset_x,16 + offset_y,1)
    oled.pixel(17 + offset_x,16 + offset_y,1)
    oled.pixel(18 + offset_x,16 + offset_y,1)
    oled.pixel(19 + offset_x,16 + offset_y,1)
    oled.pixel(20 + offset_x,16 + offset_y,1)
    oled.pixel(21 + offset_x,15 + offset_y,1)
    oled.pixel(21 + offset_x,14 + offset_y,1)

    oled.show()

def SPO2on():
    machine.Pin("A1", machine.Pin.IN)
    #machine.Pin("A6", machine.Pin.IN)



LCDamogus()
